### ISSUE TITLE
[CLOSED] Refactor scope variables

### ISSUE THREAD

**Issue by gw2efficiency-issue-importer** [gw2efficiency/issues#422]
**Original issue by [queicherius](https://github.com/queicherius)** (_Sunday Mar 30, 2014 at 14:55 GMT_)

----

- [x] Rename "dungeon" to "path" in dungeon.html (#43)
- [x] Rename everything to have more sensible names
- [x] Remove use of find-by-id methods where possible (#83)
- [x] Use correct variable types where possible (#56)

**Comment by gw2efficiency-issue-importer** [comment]
**Original comment by [queicherius](https://github.com/queicherius)** (_Saturday Apr 05, 2014 at 16:53 GMT_)

----

- [x] AuthController.js
- [x] GlobalController.js
- [x] NavigationController.js

Account
- [x] IndexController.js

Dungeons
- [x] FractalKarmaController.js
- [x] GroupsController.js
- [x] IndexController.js
- [x] InscriptionsController.js
- [x] RunsController.js
- [x] TimerController.js

Worldbosses
- [x] IndexController.js
