### ISSUE TITLE
[CLOSED] Redesign

### ISSUE THREAD

**Issue by gw2efficiency-issue-importer** [gw2efficiency/issues#430]
**Original issue by [queicherius](https://github.com/queicherius)** (_Tuesday Apr 01, 2014 at 20:40 GMT_)

----

- [ ] Reorganize CSS into folders (#55)
- [ ] Redesign the index page (#50)
- [ ] Redesign the dungeon pages
- [ ] Redesign the dialog windows (#8)
- [ ] Redesign the worldboss pages
- [ ] Redesign the account tab (#18)
- [ ] Redesign the password reset process (#17)

**Comment by gw2efficiency-issue-importer** [comment]
**Original comment by [queicherius](https://github.com/queicherius)** (_Sunday May 18, 2014 at 01:47 GMT_)

----

Display no new view on forms?
