### ISSUE TITLE
Refactor the chat

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#89]
- [x] Update the chat design (#191)
- [x] Show the online status for chat members (#192)
- [x] Add colored chat nicks (#17)
- [x] Add emojis into the chat (#88)
